### ISSUE TITLE
Got "Cannot read property 'version' of undefined" ERROR

### ISSUE THREAD

**Issue by Dandrum** [waysact/webpack-subresource-integrity#161]
Hi, i try using this plugin for NEXT.js

but i dont have installed webpack because it comes with next but even if i install it i get.

```
 TypeError: Cannot read property 'version' of undefined
at Object.<anonymous> (/frontend/node_modules/webpack-subresource-integrity/jmtp.js:10:63)
 at Module._compile (node:internal/modules/cjs/loader:1092:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
at Module.load (node:internal/modules/cjs/loader:972:32)
at Function.Module._load (node:internal/modules/cjs/loader:813:14)
at Module.require (node:internal/modules/cjs/loader:996:19)
at require (node:internal/modules/cjs/helpers:92:18)
at Object.<anonymous> (/frontend/node_modules/webpack-subresource-integrity/index.js:14:43)
at Module._compile (node:internal/modules/cjs/loader:1092:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
```

As you can see its this line from 'jmtp.js' row 10:
```
var webpackVersionComponents = require('webpack/package.json').version.split(
  '.'
);
```

Do you know any solution ?

Best,
Dan

**Comment by jscheid** [comment]
Unfortunately, Next.js doesn't have support for this plugin yet. A while ago [I've offered my help](https://github.com/vercel/next.js/discussions/23951) to make it work but never heard back.

That said, we are using the two together in an internal project. It's a bit of a hack and basically uses this plugin for dynamic imports and a custom post-processing step for top-level assets. I can't share that code here, all I can tell you is that with enough dedication you can probably make it work as well, just don't expect it to be straightforward.

As for the error, if you're using Webpack 5 (which is now the [default](https://nextjs.org/docs/messages/webpack5)) you should be using our [next branch](https://github.com/waysact/webpack-subresource-integrity/issues/144) which doesn't have the code that throws the error anymore, so hopefully will work better for you. But again, you can't really expect it to work at all, at least not out of the box.

**Comment by Dandrum** [comment]
Hey, Thanks.
I will figure out a way, thanks for your help anyways ;)

**Comment by Starefossen** [comment]
@Dandrum any chance you could share how you got this working with next.js? 🙏🏻

**Comment by Dandrum** [comment]
Yep i dont use the plugin =)
