### ISSUE TITLE
Webpack 4

### ISSUE THREAD

**Issue by jjeising** [waysact/webpack-subresource-integrity#63]
The plugin is currently missing a peer dependency for Webpack 4. [Additional changes](https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202) may be necessary.

**Comment by jscheid** [comment]
See #62. Feel free to take it for a spin and let me know if it works for you.

**Comment by jscheid** [comment]
Released in v1.1.0-rc.1. Any feedback is welcome!

**Comment by cecilemuller** [comment]
I [tried the new version](https://github.com/wildpeaks/issue-webpack4-sri) with the following dependencies:
 - **html-webpack-plugin**: `webpack-contrib/html-webpack-plugin`
 - **webpack**: `4.0.1`
 - **webpack-cli**: `2.0.9`
 - **webpack-subresource-integrity**: `1.1.0-rc.1`

But it gives this build error (on Windows 10, Node 9.6.1):

	Error: Cannot find module './util'
		at Function.Module._resolveFilename (module.js:555:15)
		at Function.Module._load (module.js:482:25)
		at Module.require (module.js:604:17)
		at require (D:\Github\issue-webpack4-sri\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
		at Object.<anonymous> (D:\Github\issue-webpack4-sri\node_modules\webpack-subresource-integrity\index.js:4:12)
		at Module._compile (D:\Github\issue-webpack4-sri\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
		at Object.Module._extensions..js (module.js:671:10)
		at Module.load (module.js:573:32)
		at tryModuleLoad (module.js:513:12)
		at Function.Module._load (module.js:505:3)
		at Module.require (module.js:604:17)
		at require (D:\Github\issue-webpack4-sri\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
		at Object.<anonymous> (D:\Github\issue-webpack4-sri\webpack.config.js:5:19)
		at Module._compile (D:\Github\issue-webpack4-sri\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
		at Object.Module._extensions..js (module.js:671:10)
		at Module.load (module.js:573:32)
		at tryModuleLoad (module.js:513:12)
		at Function.Module._load (module.js:505:3)
		at Module.require (module.js:604:17)
		at require (D:\Github\issue-webpack4-sri\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
		at WEBPACK_OPTIONS (D:\Github\issue-webpack4-sri\node_modules\webpack-cli\bin\convert-argv.js:133:13)
		at requireConfig (D:\Github\issue-webpack4-sri\node_modules\webpack-cli\bin\convert-argv.js:135:6)
		at D:\Github\issue-webpack4-sri\node_modules\webpack-cli\bin\convert-argv.js:142:17
		at Array.forEach (<anonymous>)
		at module.exports (D:\Github\issue-webpack4-sri\node_modules\webpack-cli\bin\convert-argv.js:140:15)
		at yargs.parse (D:\Github\issue-webpack4-sri\node_modules\webpack-cli\bin\webpack.js:234:39)
		at Object.parse (D:\Github\issue-webpack4-sri\node_modules\yargs\yargs.js:539:18)
		at D:\Github\issue-webpack4-sri\node_modules\webpack-cli\bin\webpack.js:212:8
		at Object.<anonymous> (D:\Github\issue-webpack4-sri\node_modules\webpack-cli\bin\webpack.js:504:3)
		at Module._compile (module.js:660:30)
		at Object.Module._extensions..js (module.js:671:10)
		at Module.load (module.js:573:32)
		at tryModuleLoad (module.js:513:12)
		at Function.Module._load (module.js:505:3)
		at Module.require (module.js:604:17)
		at require (internal/module.js:11:18)

**Comment by jscheid** [comment]
Whoops! Fixed in 1.1.0-rc.2. Thanks for letting me know.

**Comment by cecilemuller** [comment]
1.1.0-rc.2 works, awesome :tada:
