### ISSUE TITLE
Don't crash when used in non-web builds

### ISSUE THREAD

**Issue by inductor** [waysact/webpack-subresource-integrity#87]
On Nuxt.js 2.0.0

```javascript
import SriPlugin from 'webpack-subresource-integrity';
module.exports = {
  build: {
    extend(config, ctx) {
      config.output.crossOriginLoading = 'anonymous'
      config.plugins.push(new SriPlugin({
        hashFuncNames: ['sha256', 'sha384']
      }))
    }
  }
}
```

This setting triggers this error

```
✖ error TypeError: Cannot read property 'tap' of undefined
  at WebIntegrityJsonpMainTemplatePlugin.apply (/Users/inductor/vue/project/node_modules/webpack-subresource-integrity/jmtp.js:76:36)
  at SubresourceIntegrityPlugin.registerJMTP (/Users/inductor/vue/project/node_modules/webpack-subresource-integrity/index.js:302:12)
  at SubresourceIntegrityPlugin.thisCompilation (/Users/inductor/vue/project/node_modules/webpack-subresource-integrity/index.js:348:10)
  at SyncHook.eval [as call] (eval at create (/Users/inductor/vue/project/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
  at SyncHook.lazyCompileHook (/Users/inductor/vue/project/node_modules/tapable/lib/Hook.js:154:20)
  at Compiler.newCompilation (/Users/inductor/vue/project/node_modules/webpack/lib/Compiler.js:497:30)
  at hooks.beforeCompile.callAsync.err (/Users/inductor/vue/project/node_modules/webpack/lib/Compiler.js:534:29)
  at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/inductor/vue/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
  at AsyncSeriesHook.lazyCompileHook (/Users/inductor/vue/project/node_modules/tapable/lib/Hook.js:154:20)
  at Compiler.compile (/Users/inductor/vue/project/node_modules/webpack/lib/Compiler.js:529:28)
  at readRecords.err (/Users/inductor/vue/project/node_modules/webpack/lib/Compiler.js:268:11)
  at Compiler.readRecords (/Users/inductor/vue/project/node_modules/webpack/lib/Compiler.js:396:11)
  at hooks.run.callAsync.err (/Users/inductor/vue/project/node_modules/webpack/lib/Compiler.js:265:10)
  at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/inductor/vue/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
  at AsyncSeriesHook.lazyCompileHook (/Users/inductor/vue/project/node_modules/tapable/lib/Hook.js:154:20)
  at hooks.beforeRun.callAsync.err (/Users/inductor/vue/project/node_modules/webpack/lib/Compiler.js:262:19)
```

**Comment by jscheid** [comment]
You can fix this by adding the plugin only for the client build, not for the server build:

```js
    extend(config, ctx) {
      config.output.crossOriginLoading = "anonymous";
      if (ctx.isClient) {
        config.plugins.push(
          new SriPlugin({
            hashFuncNames: ["sha256", "sha384"]
          })
        );
      }
    }
```

We should handle this case more gracefully though, I'll change the issue title to reflect this.

**Comment by jscheid** [comment]
It seems they bypass html-webpack-plugin altogether and use their own template rendering: 
https://github.com/vuejs/vue/blob/52719ccab8fccffbdf497b96d3731dc86f04c1ce/src/server/template-renderer/index.js#L209

If so there's not much this plugin can do. I suppose you could ask them to make `script` (and `link`) rendering more configurable, then somebody could write a plugin for Vue that adds the `integrity` attribute.

But again, I don't know much about Nuxt or Vue so this might be completely off base.
